apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitserver
spec:
  volumeClaimTemplates:
  - metadata:
      name: repos
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
      storageClassName: ebs-csi-retain
