apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitserver
spec:
  template:
    spec:
      containers:
      - name: gitserver
        resources:
          requests:
            cpu: 4
            memory: 16Gi
          limits:
            memory: 22Gi
  volumeClaimTemplates:
  - metadata:
      name: repos
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
      storageClassName: ebs-csi-retain
