apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbols
spec:
  template:
    spec:
      containers:
      - name: symbols
        resources:
          requests:
            cpu: 250m
            ephemeral-storage: "10G"
            memory: 500M
