apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbols
spec:
  template:
    spec:
      containers:
      - name: symbols
        resources:
          requests:
            cpu: 2
            memory: 2Gi
            ephemeral-storage: "10G"
          limits:
            cpu: 4
            memory: 8Gi
