apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-store
spec:
  template:
    spec:
      containers:
      - name: redis-store
        resources:
          requests:
            cpu: 250m
