apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcher
spec:
  template:
    spec:
      containers:
      - name: searcher
        resources:
          limits:
            ephemeral-storage: "5G"
          requests:
            cpu: 250m
            ephemeral-storage: "2G"
