apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeinsights-db
spec:
  template:
    spec:
      containers:
        - name: codeinsights-db
          resources:
            requests:
              cpu: 500m
