apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-updater
spec:
  template:
    spec:
      containers:
      - name: repo-updater
        resources:
          requests:
            cpu: 250m
