apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sourcegraph-frontend
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - sourcegraph.example.com
    secretName: sourcegraph-tls
