apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexed-search
spec:
  volumeClaimTemplates:
  - metadata:
      labels:
        deploy: sourcegraph
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
      storageClassName: ebs-csi-retain
