# - op: add
#   path: "/spec/template/spec/containers/0/env/-"
#   value:
#     name: EXECUTOR_METRIC_AWS_ACCESS_KEY_ID
#     valueFrom:
#       secretKeyRef:
#         name: metrics-credentials
#         key: EXECUTOR_METRIC_AWS_ACCESS_KEY_ID
# - op: add
#   path: "/spec/template/spec/containers/0/env/-"
#   value:
#     name: EXECUTOR_METRIC_AWS_SECRET_ACCESS_KEY
#     valueFrom:
#       secretKeyRef:
#         name: metrics-credentials
#         key: EXECUTOR_METRIC_AWS_SECRET_ACCESS_KEY
# - op: add
#   path: "/spec/template/spec/containers/0/env/-"
#   value:
#     name: EXECUTOR_METRIC_ENVIRONMENT_LABEL
#     valueFrom:
#       secretKeyRef:
#         name: metrics-credentials
#         key: EXECUTOR_METRIC_ENVIRONMENT_LABEL
# - op: add
#   path: "/spec/template/spec/containers/0/env/-"
#   value:
#     name: EXECUTOR_METRIC_AWS_NAMESPACE
#     value: sourcegraph-executor
# - op: add
#   path: "/spec/template/spec/containers/0/env/-"
#   value:
#     name: EXECUTOR_METRIC_AWS_REGION
#     value: us-east-1
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: PRECISE_CODE_INTEL_AUTO_INDEXING_TASK_INTERVAL
    value: 1m
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: PRECISE_CODE_INTEL_AUTO_INDEXING_REPOSITORY_PROCESS_DELAY
    value: 10s
