apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sourcegraph
resources:
  - sourcegraph.Namespace.yaml
  - ../namespaced
patchesStrategicMerge:
  - cadvisor/cadvisor.ClusterRoleBinding.yaml
  - codeinsights-db/codeinsights-db.Deployment.yaml
  - codeinsights-db/codeinsights-db.PersistentVolumeClaim.yaml
  - codeintel-db/codeintel-db.Deployment.yaml
  - codeintel-db/codeintel-db.PersistentVolumeClaim.yaml
  - frontend/sourcegraph-frontend.Deployment.yaml
  - frontend/sourcegraph-frontend.Ingress.yaml
  - gitserver/gitserver.StatefulSet.yaml
  - grafana/grafana.StatefulSet.yaml
  - indexed-search/indexed-search.StatefulSet.yaml
  - minio/minio.Deployment.yaml
  - minio/minio.PersistentVolumeClaim.yaml
  - pgsql/pgsql.Deployment.yaml
  - pgsql/pgsql.PersistentVolumeClaim.yaml
  - precise-code-intel/worker.Deployment.yaml
  - prometheus/prometheus.ClusterRoleBinding.yaml
  - prometheus/prometheus.ConfigMap.yaml
  - prometheus/prometheus.Deployment.yaml
  - prometheus/prometheus.PersistentVolumeClaim.yaml
  - redis/redis-cache.Deployment.yaml
  - redis/redis-cache.PersistentVolumeClaim.yaml
  - redis/redis-store.Deployment.yaml
  - redis/redis-store.PersistentVolumeClaim.yaml
  - repo-updater/repo-updater.Deployment.yaml
  - searcher/searcher.Deployment.yaml
  - symbols/symbols.Deployment.yaml
  - worker/worker.Deployment.yaml
patches:
  - target:
      kind: Ingress
      name: sourcegraph-frontend
    path: frontend/sourcegraph-frontend.Ingress-patch.json
