apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sourcegraph
resources:
  - sourcegraph.Namespace.yaml
  - ../namespaced
patchesStrategicMerge:
  - cadvisor/cadvisor.ClusterRoleBinding.yaml
  - codeinsights-db/codeinsights-db.PersistentVolumeClaim.yaml
  - codeintel-db/codeintel-db.PersistentVolumeClaim.yaml
  - frontend/sourcegraph-frontend.Deployment.yaml
  - frontend/sourcegraph-frontend.Ingress.yaml
  - gitserver/gitserver.StatefulSet.yaml
  - grafana/grafana.StatefulSet.yaml
  - indexed-search/indexed-search.StatefulSet.yaml
  - minio/minio.PersistentVolumeClaim.yaml
  - pgsql/pgsql.Deployment.yaml
  - pgsql/pgsql.PersistentVolumeClaim.yaml
  - precise-code-intel/worker.Deployment.yaml
  - prometheus/prometheus.ClusterRoleBinding.yaml
  - prometheus/prometheus.ConfigMap.yaml
  - prometheus/prometheus.PersistentVolumeClaim.yaml
  - redis/redis-cache.PersistentVolumeClaim.yaml
  - redis/redis-store.PersistentVolumeClaim.yaml
  - searcher/searcher.Deployment.yaml
  - symbols/symbols.Deployment.yaml
  - worker/worker.Deployment.yaml
patches:
  - target:
      kind: Ingress
      name: sourcegraph-frontend
    path: frontend/sourcegraph-frontend.Ingress-patch.json
  - target:
      kind: DaemonSet
      name: cadvisor
    path: resources-patches/cadvisor.DaemonSet.json
  - target:
      kind: Deployment
      name: codeinsights-db
    path: resources-patches/codeinsights-db.Deployment.json
  - target:
      kind: Deployment
      name: codeintel-db
    path: resources-patches/codeintel-db.Deployment.json
  - target:
      kind: Deployment
      name: sourcegraph-frontend
    path: resources-patches/sourcegraph-frontend.Deployment.json
  - target:
      kind: Deployment
      name: github-proxy
    path: resources-patches/github-proxy.Deployment.json
  - target:
      kind: StatefulSet
      name: gitserver
    path: resources-patches/gitserver.StatefulSet.json
  - target:
      kind: StatefulSet
      name: grafana
    path: resources-patches/grafana.StatefulSet.json
  - target:
      kind: StatefulSet
      name: indexed-search
    path: resources-patches/indexed-search.StatefulSet.json
  - target:
      kind: Deployment
      name: jaeger
    path: resources-patches/jaeger.Deployment.json
  - target:
      kind: Deployment
      name: minio
    path: resources-patches/minio.Deployment.json
  - target:
      kind: Deployment
      name: pgsql
    path: resources-patches/pgsql.Deployment.json
  - target:
      kind: Deployment
      name: precise-code-intel-worker
    path: resources-patches/precise-code-intel-worker.Deployment.json
  - target:
      kind: Deployment
      name: prometheus
    path: resources-patches/prometheus.Deployment.json
  - target:
      kind: Deployment
      name: redis-cache
    path: resources-patches/redis-cache.Deployment.json
  - target:
      kind: Deployment
      name: redis-store
    path: resources-patches/redis-store.Deployment.json
  - target:
      kind: Deployment
      name: repo-updater
    path: resources-patches/repo-updater.Deployment.json
  - target:
      kind: Deployment
      name: searcher
    path: resources-patches/searcher.Deployment.json
  - target:
      kind: Deployment
      name: symbols
    path: resources-patches/symbols.Deployment.json
  - target:
      kind: Deployment
      name: syntect-server
    path: resources-patches/syntect-server.Deployment.json
  - target:
      kind: Deployment
      name: worker
    path: resources-patches/worker.Deployment.json
