apiVersion: apps/v1
kind: Deployment
metadata:
  name: precise-code-intel-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: precise-code-intel-worker
        resources:
          requests:
            cpu: 4
            memory: 2Gi
          limits:
            cpu: 4
            memory: 4Gi
