apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-runner
spec:
  template:
    spec:
      containers:
      - name: query-runner
        resources:
          requests:
            cpu: 100m
