apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
  labels:
    queue: codeintel
spec:
  replicas: 3
  template:
    metadata:
      labels:
        queue: codeintel
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: queue
                      operator: In
                      values:
                        - codeintel
      containers:
        - name: executor
          resources:
            requests:
              cpu: "1000m"
              memory: 2Gi
          env:
            - name: EXECUTOR_FRONTEND_URL
              value: http://sourcegraph-frontend:30080
            - name: EXECUTOR_QUEUE_NAME
              value: "codeintel"
            - name: EXECUTOR_FRONTEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: executor-secret
                  key: EXECUTOR_FRONTEND_PASSWORD
