apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: executor
          resources:
            requests:
              cpu: "1000m"
              memory: 2Gi
          livenessProbe: null
          readinessProbe: null
          env:
            - name: EXECUTOR_FRONTEND_URL
              value: http://sourcegraph-frontend:30080
            - name: EXECUTOR_QUEUE_NAME
              value: "codeintel"
            - name: EXECUTOR_FRONTEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: executor-secret
                  key: EXECUTOR_FRONTEND_PASSWORD
